# Generated by Django 4.1.10 on 2023-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
