# Generated by Django 4.1.10 on 2023-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('nutrition', models.EmailField(default='', max_length=30)),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=30)),
                ('Name', models.CharField(default='', max_length=30)),
                ('Bio', models.CharField(default='', max_length=250)),
                ('Email', models.EmailField(default='', max_length=250)),
                ('Phone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('Experience', models.IntegerField(default=0)),
                ('Skill1', models.CharField(default='', max_length=20)),
                ('Skill2', models.CharField(default='', max_length=20)),
                ('Skill3', models.CharField(default='', max_length=20)),
                ('Skill4', models.CharField(default='', max_length=20)),
                ('Rate_skill1', models.CharField(default='', max_length=20)),
                ('Rate_skill2', models.CharField(default='', max_length=20)),
                ('Rate_skill3', models.CharField(default='', max_length=20)),
                ('Rate_skill4', models.CharField(default='', max_length=20)),
                ('Days_of_Program', models.IntegerField(default=0)),
                ('Customers', models.IntegerField(default=0)),
                ('Sessions', models.IntegerField(default=0)),
                ('link_Calendly', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition_Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='', max_length=30)),
                ('Last_name', models.CharField(default='', max_length=30)),
                ('Country', models.CharField(default='', max_length=25)),
                ('Email', models.EmailField(default='', max_length=250)),
                ('Phone', models.IntegerField(default=0)),
                ('Degree', models.CharField(default='', max_length=15)),
                ('Gender', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(default='', max_length=15)),
                ('Experience', models.IntegerField(default=0)),
                ('Password', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
